export async function onRequestOptions() {
  return new Response(null, {
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    },
  });
}

function corsHeaders() {
  return {
    'Access-Control-Allow-Origin': '*',
    'Content-Type': 'application/json',
  };
}

export async function onRequestPost({ request, env }) {
  try {
    const { type, prompt, image, studentComment } = await request.json();
    const apiKey = env.GEMINI_API_KEY;

    if (!apiKey) {
      return new Response(JSON.stringify({ error: 'GEMINI_API_KEY is not set in Cloudflare' }), { status: 500, headers: corsHeaders() });
    }

    let finalPrompt = '';
    let contents = [];

    if (type === 'generate') {
      // 텍스트로 그림 생성
      finalPrompt = `
        어린이 미술 수업을 위한 그림을 그려줘. 
        아이의 코멘트: "${studentComment || ''}"
        이 아이의 성향과 창의성을 고려해서, 이 아이가 그린 것 같은 따뜻하고 생동감 넘치는 어린이 미술 작품 스타일(수채화, 크레파스 또는 깔끔한 일러스트 느낌)로 그려줘.
        배경은 너무 복잡하지 않게, 아이의 작품 세계가 돋보이도록 해줘.
      `;
      contents = [{
        parts: [{ text: finalPrompt }]
      }];
    } else if (type === 'upscale') {
      // 이미지 기반 퀄업 (Image-to-Image)
      if (!image) throw new Error('No image provided for upscale');
      
      const [mime, base64] = image.split(',');
      const mimeType = mime.match(/:(.*?);/)[1];

      finalPrompt = "이 어린이 그림을 웹툰이나 깔끔한 디지털 일러스트 스타일로 재해석해서 고품질로 다시 그려줘. 아이의 원래 의도와 구도는 최대한 유지하되, 선과 색감을 전문가 수준으로 깔끔하게 다듬어줘.";
      
      contents = [{
        parts: [
          { text: finalPrompt },
          {
            inlineData: {
              mimeType: mimeType,
              data: base64
            }
          }
        ]
      }];
    }

    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: contents,
        generationConfig: {
          responseModalities: ["IMAGE"]
        }
      })
    });

    if (!response.ok) {
      const err = await response.text();
      console.error('Gemini Error:', err);
      throw new Error('Gemini API request failed');
    }

    const json = await response.json();
    const imagePart = json.candidates[0].content.parts.find(p => p.inlineData);

    if (!imagePart) {
      throw new Error('No image was generated by Gemini');
    }

    return new Response(JSON.stringify({ 
      image: `data:${imagePart.inlineData.mimeType};base64,${imagePart.inlineData.data}` 
    }), { headers: corsHeaders() });

  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), { status: 500, headers: corsHeaders() });
  }
}
